CREATE TABLE ACCOUNTS (
    ACCOUNT_ID      NUMBER PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR2(100) NOT NULL,
    ACCOUNT_TYPE    VARCHAR2(20) NOT NULL,
    BALANCE         NUMBER(12,2) NOT NULL
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID     NUMBER PRIMARY KEY,
    EMPLOYEE_NAME   VARCHAR2(100) NOT NULL,
    DEPARTMENT      VARCHAR2(50) NOT NULL,
    SALARY          NUMBER(12,2) NOT NULL
);