CREATE TABLE Employee (
    emp_id NUMBER PRIMARY KEY,
    emp_name VARCHAR2(50) NOT NULL,
    emp_dept VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    salary NUMBER(10,2) CHECK (salary > 0),
    joining_date DATE,
    created_date DATE
);

CREATE TABLE Employee_Audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id NUMBER,
    old_salary NUMBER(10,2),
    new_salary NUMBER(10,2),
    action_type VARCHAR2(20),
    action_date DATE
);

